-- DEM SO LUONG KHACH HANG CO TRONG BANG
SELECT COUNT(*) AS[NUMBER CUSTOMER]
FROM dbo.Customers

SELECT COUNT([CustomerID]) AS[NUMBER CUSTOMER]
FROM dbo.Customers

-- TINH TONG VAN CHUYEN(FREIGHT) CUA TAT CA CAC ĐON DAT HANG
SELECT SUM([Freight]) AS[SUMFREIGHT]
FROM [dbo].[Orders]

-- TINH SO LUONG TRUNG BINH DAT HANG CUA TAT CA SAN PHAM TRONG ORDER DETAIL
SELECT AVG([Quantity]) AS[AVG QUANTITTY]
FROM [dbo].[Order Details]

--DEM SO LUONG TỊNH TONG SO LUONG HANG TRONG KHO
-- VA AVG CUA CAC SAN PHAM CO TRONG BANG PRODUCT
SELECT COUNT(*)AS[NUMBERCOUNT], SUM([UnitsInStock]) AS [NUMBER UNITSINSTOCK], AVG([UnitPrice]) AS [NUMBER UNITPRICE]
FROM[dbo].[Products]

-- DEM SO LUONG ORDERS BANG HAI CACH
SELECT COUNT(*) AS[NUMBER COUNT]
FROM[dbo].[Orders]

SELECT COUNT ([OrderID])
FROM [dbo].[Orders] AS[NUMBER COUNT]

-- TU  BANG ORDER DETAILS TINH TRUNG BINH CHO COT UNITPRICE VA SUM QUANTITY
SELECT AVG ([UnitPrice]) AS [NUMBER UNITPRICE],
       SUM ([Quantity]) AS [NUMBER QUANTITY]
FROM [dbo].[Order Details]